name: LineageOS CI (A1000)

on:
  workflow_dispatch:
jobs:
  build:
    name: LineageOS Build CI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
    - name: Check Out
      uses: actions/checkout@v3
    - name: Cleanup
      uses: rokibhasansagar/slimhub_actions@main
    - name: Installing JDK 7 + Build Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install gperf maven gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib libc6-dev lib32ncurses5-dev x11proto-core-dev libx11-dev tree lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc bc ccache lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk3.0-gtk3-dev libxml2 lzop pngcrush schedtool squashfs-tools imagemagick libbz2-dev lzma ncftp qemu-user-static libstdc++-10-dev libncurses5 axel python
        mkdir ~/.jdk_7
        cd ~/.jdk_7
        axel -q -n $(nproc --all) https://download.java.net/openjdk/jdk7u75/ri/openjdk-7u75-b13-linux-x64-18_dec_2014.tar.gz
        tar -xzf openjdk-7u75-b13-linux-x64-18_dec_2014.tar.gz
    - name: Syncing LineageOS sources
      run: |
        mkdir ~/TWRP
        cd ~/TWRP
        mkdir ~/.bin
        curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
        python3 ~/.bin/repo init --depth=1 -u https://github.com/LineageOS/android.git -b cm-13.0
        git clone https://github.com/unlegacy-devices/android_device_lenovo_a1000 -b cm-13.0 ~/TWRP/device/lenovo/a1000
        git clone https://github.com/unlegacy-devices/android_kernel_samsung_grandprimeve3g -b cm-13.0 ~/TWRP/kernel/samsung/grandprimeve3g
        git clone https://github.com/unlegacy-devices/android_vendor_lenovo_a1000 -b cm-13.0 ~/TWRP/vendor/lenovo/a1000
        git clone --depth 1 --branch android-6.0.1_r40 --single-branch https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-eabi-4.8 /opt/toolchains/arm-eabi-4.8/
        python3 ~/.bin/repo sync -c --force-sync --optimized-fetch --no-tags --no-clone-bundle --prune -j$(nproc --all)
    - name: Building LineageOS
      run: |
        OLDPATH=$PATH
        OLDJAVAHOME=$JAVA_HOME
        export PATH="$HOME/.jdk_7/java-se-7u75-ri/bin:$PATH"
        export JAVA_HOME="$HOME/.jdk_7/java-se-7u75-ri"
        cd ~/TWRP
        git clone https://github.com/unlegacy-devices/android_device_lenovo_scx30g2-common -b cm-13.0 ~/TWRP/device/lenovo/scx30g2-common
        git clone https://github.com/unlegacy-devices/android_device_lenovo_scx35-common -b cm-13.0 ~/TWRP/device/lenovo/scx35-common
        git clone https://github.com/unlegacy-devices/android_vendor_lenovo_scx30g2-common -b cm-13.0 ~/TWRP/vendor/lenovo/scx30g2-common
        git clone https://github.com/unlegacy-devices/android_device_lenovo_sprd-common -b cm-13.0 ~/TWRP/device/lenovo/sprd-common
        git clone https://github.com/diepquynh/android_hardware_sprd -b cm-13.0 ~/TWRP/hardware/sprd
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        export LC_ALL=C
        lunch lineage_a1000-eng
        make -j$(nproc --all) otapackage
        export PATH=$OLDPATH
        export JAVA_HOME=$OLDJAVAHOME
    - name: CD to LineageOS builds
      run: |
         cd $OUT
         ls
    - name: Uploading LineageOS builds
      uses: actions/upload-artifact@v2
      with:
        name: lineageos
        path: /home/runner/TWRP/out/target/product/a1000/*.zip
    - name: Uploading LineageOS Recovery builds
      uses: actions/upload-artifact@v2
      with:
        name: lineagerecovery
        path: /home/runner/TWRP/out/target/product/a1000/recovery.*
